workflows:
  ios-vpn-build:
    name: Build iOS VPN app
    environment:
      flutter: "3.29.2"
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build unsigned IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
