name: my_vpn_app
description: "A VPN project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  openvpn_flutter: ^1.3.4
  lucide_icons: ^0.244.0
  app_links: ^3.4.3
  http: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/load_back.png
    - assets/images/load_back_only_color.png
    - assets/images/logo.png
#    - assets/icon/app_icon.png

  fonts:
    - family: Laila
      fonts:
        - asset: assets/fonts/Laila/Laila-Regular.ttf
        - asset: assets/fonts/Laila/Laila-Bold.ttf
          weight: 700
        - asset: assets/fonts/Laila/Laila-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Laila/Laila-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_3.png"
  adaptive_icon_foreground: "assets/images/logo_3.png"
  adaptive_icon_background: "assets/images/load_back_only_color.png"


flutter_native_splash:
  color: "#080B14"
  image: assets/images/load_back_only_color.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  branding: assets/images/lordvpn.png

  android_12:
    color: "#080B14"
    image: assets/images/load_back_only_color.png
    branding: assets/images/lordvpn.png
